/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './hoc/**/*.{html,js,ts,jsx,tsx}',
    './pages/**/*.{html,js,ts,jsx,tsx}',
    './components/**/*.{html,js,ts,jsx,tsx}',
    './node_modules/react-tailwindcss-datepicker/dist/index.esm.js'
  ],
  theme: {
    extend: {
      gridTemplateColumns: {
        fluid: 'repeat(auto-fill, minmax(290px, 1fr))',
        teamfluid: 'repeat(auto-fill, minmax(250px, 1fr))'
      }
    },
    screens: {
      ss: '320px',
      xs: '425px',
      xxs: '639px',
      sm: '640px', //=> @media (min-width: 640px) { ... }
      md: '768px', // => @media (min-width: 768px) { ... }
      lg: '1024px', // => @media (min-width: 1024px) { ... }
      xl: '1280px', // => @media (min-width: 1280px) { ... }
      '2xl': '1536px'
    }
  },
  daisyui: {
    themes: [
      {
        sabuydee_dark: {
          '--main-color': '#90C8FF',
          primary: '#90C8FF',
          secondary: '#C7E8FF',
          accent: '#f4c20d',
          'base-100': '#121213',
          // 'base-200': '#5A5A62',
          neutral: '#f5f6fa',
          info: '#117AEE',
          success: '#39CA5F',
          warning: '#F4A526',
          error: '#F42B1F',
          theme: '#f5f6fa',
          '--bg-container': '#161d23',
          '--bg-panel': '#000000',
          '--text': '#084A89',
          '--bg-color': '#121213',
          '--bg-menu': '#ededed',
          '--active-menu': '#90C8FF',
          '--input-text': '#ffffff',
          '--input-bg': '#5A5A62',
          '--login-bg': '#C7E8FF',
          '--bg-breadcrumbs': '#CFE7FF',
          '--border-color': '#46464D',
          '--bt-action': '#CFE7FF',
          '--bt-text': '#000000',
          '--chart-text': "#e5e7eb"
        },
        sabuydee_light: {
          '--main-color': '#1D5D9B',
          primary: '#1D5D9B',
          secondary: '#75C2F6',
          accent: '#bc23db',
          neutral: '#2d2438',
          'base-100': '#f5f6fa',
          // 'base-200': '#727279',
          info: '#6180e5',
          success: '#39CA5F',
          warning: '#f3ba59',
          error: '#e36363',
          theme: '#000000',
          '--bg-container': '#F6FBFF',
          '--bg-panel': '#ffffff',
          '--text': '#00376D',
          '--bg-color': '#f5f6fa',
          '--bg-menu': '#727279',
          '--active-menu': '#e5e7eb',
          '--input-text': '#000000',
          '--input-bg': '#f5f6fa',
          '--login-bg': '#fff', //90C8FF
          '--bg-breadcrumbs': '#90C8FF',
          '--border-color': '#D4D5DF',
          '--bt-action': '#00376D',
          '--bt-text': '#ffffff',
          '--chart-text': "#00376D"
        },
        speedkub_dark: {
          '--main-color': '#E6564E',
          primary: '#E6564E',
          secondary: '#36D399',
          accent: '#f4c20d',
          'base-100': '#121213',
          // 'base-200': '#5A5A62',
          neutral: '#f5f6fa',
          info: '#3ABFF8',
          success: '#36D399',
          warning: '#FBBD23',
          error: '#F87272',
          theme: '#f5f6fa',
          '--bg-container': '#231618',
          '--bg-panel': '#000000',
          '--text': '#f5f6fa',
          '--bg-color': '#38383C',
          '--bg-menu': '#ededed',
          '--active-menu': '#5A5A62',
          '--input-text': '#ffffff',
          '--input-bg': '#ededed',
          '--login-bg': '#C7E8FF',
          '--bg-breadcrumbs': '#d1768a',
          '--border-color': '#46464D',
          '--bt-text': '#000000',
          '--chart-text': "#e5e7eb"
        },
        speedkub_light: {
          '--main-color': '#E6564E',
          primary: '#E6564E',
          secondary: '#0bb8e8',
          accent: '#bc23db',
          neutral: '#2d2438',
          'base-100': '#f5f6fa',
          // 'base-200': '#727279',
          info: '#6180e5',
          success: '#39CA5F',
          warning: '#f3ba59',
          error: '#e36363',
          theme: '#000000',
          '--bg-container': '#F6FBFF',
          '--bg-panel': '#ffffff',
          '--text': '#000000',
          '--bg-color': '#f5f6fa',
          '--bg-menu': '#727279',
          '--active-menu': '#e5e7eb',
          '--input-text': '#000000',
          '--input-bg': '#dddddd',
          '--login-bg': '#90C8FF',
          '--bg-breadcrumbs': '#ffbecc',
          '--border-color': '#D4D5DF',
          '--bt-text': '#ffffff',
          '--chart-text': "#121213"
        },
        fiittoken_dark: {
          '--main-color': '#33A44D',
          primary: '#33A44D',
          secondary: '#36D399',
          accent: '#f4c20d',
          'base-100': '#121213',
          // 'base-200': '#5A5A62',
          neutral: '#f5f6fa',
          info: '#3ABFF8',
          success: '#36D399',
          warning: '#FBBD23',
          error: '#F87272',
          theme: '#f5f6fa',
          '--bg-container': '#172316',
          '--bg-panel': '#000000',
          '--text': '#f5f6fa',
          '--bg-color': '#38383C',
          '--bg-menu': '#ededed',
          '--active-menu': '#5A5A62',
          '--input-text': '#ffffff',
          '--input-bg': '#ededed',
          '--login-bg': '#C7E8FF',
          '--bg-breadcrumbs': '#468d56',
          '--border-color': '#46464D',
          '--bt-text': '#000000',
          '--chart-text': "#e5e7eb"
        },
        fiittoken_light: {
          '--main-color': '#33A44D',
          primary: '#33A44D',
          secondary: '#0bb8e8',
          accent: '#bc23db',
          neutral: '#2d2438',
          'base-100': '#f5f6fa',
          // 'base-200': '#727279',
          info: '#6180e5',
          success: '#39CA5F',
          warning: '#f3ba59',
          error: '#e36363',
          theme: '#000000',
          '--bg-container': '#F6FBFF',
          '--bg-panel': '#ffffff',
          '--text': '#000000',
          '--bg-color': '#f5f6fa',
          '--bg-menu': '#727279',
          '--active-menu': '#e5e7eb',
          '--input-text': '#000000',
          '--input-bg': '#dddddd',
          '--login-bg': '#fff',//'#90C8FF'
          '--bg-breadcrumbs': '#6fde88',
          '--border-color': '#D4D5DF',
          '--bt-text': '#ffffff',
          '--chart-text': "#121213"
        },
        sabuymoney_dark: {
          '--main-color': '#117AEE',
          primary: '#117AEE',
          secondary: '#36D399',
          accent: '#f4c20d',
          'base-100': '#121213',
          // 'base-200': '#5A5A62',
          neutral: '#f5f6fa',
          info: '#3ABFF8',
          success: '#36D399',
          warning: '#FBBD23',
          error: '#F87272',
          theme: '#f5f6fa',
          '--bg-container': '#161923',
          '--bg-panel': '#000000',
          '--text': '#f5f6fa',
          '--bg-color': '#38383C',
          '--bg-menu': '#ededed',
          '--active-menu': '#5A5A62',
          '--input-text': '#ffffff',
          '--input-bg': '#ededed',
          '--login-bg': '#C7E8FF',
          '--bg-breadcrumbs': '#2a639c',
          '--border-color': '#46464D',
          '--bt-text': '#000000',
          '--chart-text': "#e5e7eb"
        },
        sabuymoney_light: {
          '--main-color': '#117AEE',
          primary: '#117AEE',
          secondary: '#0bb8e8',
          accent: '#bc23db',
          neutral: '#2d2438',
          'base-100': '#f5f6fa',
          // 'base-200': '#727279',
          info: '#6180e5',
          success: '#39CA5F',
          warning: '#f3ba59',
          error: '#e36363',
          theme: '#000000',
          '--bg-container': '#F6FBFF',
          '--bg-panel': '#ffffff',
          '--text': '#000000',
          '--bg-color': '#f5f6fa',
          '--bg-menu': '#727279',
          '--active-menu': '#e5e7eb',
          '--input-text': '#000000',
          '--input-bg': '#dddddd',
          '--login-bg': '#90C8FF',
          '--bg-breadcrumbs': '#cde6ff',
          '--border-color': '#D4D5DF',
          '--bt-text': '#ffffff',
          '--chart-text': "#121213"
        }
      }
    ]
  },
  plugins: [require('daisyui'), require('@tailwindcss/forms')]
};
